site_name: "TMOEG | IT сообщество"
copyright: Copyright &copy; 2022 Under CC-BY-NC 4.0

# Репозиторий
repo_url: https://github.com/tmoeg/site-contents
edit_uri: ""

site_dir: site

# Раскомментируйте и вставьте путь для тестирования локальной документации
# docs_dir: 

plugins:
  - search
  - awesome-pages
  - autolinks
  - macros:
      render_by_default: false
  - i18n:
      default_language: ru
      languages:
        ru: Русский
        en: English
  # Аддон  конверсии ассетов в webp
  # - images-to-webp:
  #     extensions:
  #       - png
  #     img_dir:
  # - exclude:
  #     glob:
  #       # - README.md
  #       - "*.png"
  #       - "*.jpg"

extra:
  # Поддержка локализации
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Русский
  #     link: /
  #     lang: ru
  social:
    - icon: fontawesome/brands/creative-commons-by
      link: http://creativecommons.org/licenses/by-nc/4.0/
    - icon: fontawesome/brands/creative-commons-nc
      link: http://creativecommons.org/licenses/by-nc/4.0/

theme:
  name: material
  language: ru
  favicon: assets/dots.png
  logo: assets/dots.png
  icon:
    repo: fontawesome/brands/github-square
    alternate: fontawesome/solid/language
  font:
    text: Golos Text
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  
  palette: 
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  
extra_css:
- extra.css

markdown_extensions:
  - attr_list
  - def_list
  - tables
  - md_in_html
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  # - pymdownx.snippets:
  #     auto_append:
  #       - abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
